Point,Payment,Order DAO,DTO,sql 수정
miniBcake/bungeobbang pull request #70
Opened 2024-10-30 09:05 UTC by HRong98

Point,Payment,Order DAO,DTO,sql 수정

sql trigger 생성

2024-10-30 09:07 UTC, mijin226 approved these changes

2024-10-30 09:08 UTC, JJH0355 submitted a review, later dismissed

2024-10-30 09:20 UTC, miniBcake requested changes

2024-10-30 09:20 UTC, miniBcake commented on src/main/java/com/bungeobbang/app/biz/sql/BB_TABLE.sql
> +-- trigger
join 조건 문제

2024-10-30 09:43 UTC, HRong98 reviewed
수정완료

2024-10-30 10:58 UTC, miniBcake approved these changes

2024-10-30 23:59 UTC, JJH0355 submitted a review, later dismissed

2024-10-31 00:54 UTC, mijin226 submitted a review, later dismissed

2024-10-31 00:54 UTC, Jaejune0302 approved these changes

2024-10-31 01:08 UTC, JELKOV approved these changes

2024-10-31 01:09 UTC, mijin226 approved these changes

2024-10-31 01:09 UTC, miniBcake approved these changes

2024-10-31 01:10 UTC, JJH0355 approved these changes

2024-10-31 01:50 UTC, Jaejune0302 approved these changes

2024-10-31 01:50 UTC, merged